export const WINDOWS_SIGNIN_FILENAME = "Complete-CCTV-Tailscale-Signin.cmd";
export const WINDOWS_SIGNIN_SCRIPT_MARKER = "___HOMEPICTURES_PS1___";

export function tailscaleProfilesLookUnconfigured(parsed: unknown): boolean {
  return Array.isArray(parsed) && parsed.length === 0;
}

function escapeSingleQuotedPowershell(value: string): string {
  return value.replace(/'/g, "''");
}

export function buildWindowsSigninScript(authKey: string): string {
  const encodedKey = escapeSingleQuotedPowershell(authKey);

  return `#Requires -Version 5.1
<#
.SYNOPSIS
  Signs a fresh Tailscale Windows client into Camera Access.

.DESCRIPTION
  Generated by the authenticated HomePictures setup portal. Delete this file
  after use. It contains a sign-in secret.

  If Tailscale already has an account, this script makes no login changes.
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$AuthKeyMaterial = '${encodedKey}'
$ReturnUrl = 'https://cctv.mpdee.uk/setup'
$script:SkipWait = $false

function Write-Info([string]$Message) {
    Write-Host $Message
}

function Write-WarnLine([string]$Message) {
    Write-Host $Message
}

function Wait-ForReader {
    Write-Host ""
    Write-Host "Press Enter to close this window."
    try {
        [void][Console]::ReadLine()
    } catch {
        Start-Sleep -Seconds 8
    }
}

function Test-AllowedSetupReturnUrl {
    param([Parameter(Mandatory)][string]$Url)

    try {
        $uri = [uri]$Url
    } catch {
        return $false
    }

    if (-not $uri.IsAbsoluteUri -or $uri.Scheme -cne 'https' -or $uri.UserInfo) {
        return $false
    }

    $hostOk = $false
    foreach ($name in @('cctv.mpdee.uk', 'localhost', '127.0.0.1')) {
        if ($uri.Host -ceq $name) {
            $hostOk = $true
        }
    }
    if (-not $hostOk) {
        return $false
    }

    return ($uri.AbsolutePath.TrimEnd('/') -ceq '/setup')
}

function Get-SetupWizardUri {
    param([string]$Flag)

    if (-not (Test-AllowedSetupReturnUrl $ReturnUrl)) {
        throw "The setup return URL is not allowed."
    }
    if ($Flag -and $Flag -notin @('installed', 'signedin')) {
        throw "Unsupported setup return flag."
    }

    $uri = [uri]$ReturnUrl
    $origin = $uri.GetLeftPart([System.UriPartial]::Authority)
    if ($Flag) {
        return [uri]($origin + '/setup?windows=' + $Flag)
    }
    return [uri]($origin + '/setup')
}

function Open-SetupWizard {
    param([string]$Flag)

    $target = Get-SetupWizardUri -Flag $Flag
    Start-Process $target.AbsoluteUri | Out-Null
    $script:SkipWait = $true
}

function Get-TailscaleExe {
    $candidates = @(
        (Join-Path $env:ProgramFiles 'Tailscale\\tailscale.exe')
    )
    if (\${env:ProgramFiles(x86)}) {
        $candidates += (Join-Path \${env:ProgramFiles(x86)} 'Tailscale\\tailscale.exe')
    }

    foreach ($path in $candidates) {
        if ($path -and (Test-Path -LiteralPath $path)) {
            return $path
        }
    }

    return $null
}

function Test-StatusLooksUnconfigured {
    param([Parameter(Mandatory)][string]$Exe)

    try {
        $raw = & $Exe status --json 2>&1 | Out-String
        if (-not $raw) {
            return $false
        }

        $status = $raw | ConvertFrom-Json
        if ($status.BackendState -in @('Running', 'Starting')) {
            return $false
        }

        $loginName = $null
        if ($null -ne $status.User) {
            $loginName = $status.User.LoginName
        }

        $tailnetName = $null
        if ($null -ne $status.CurrentTailnet) {
            $tailnetName = $status.CurrentTailnet.Name
        }

        if ($loginName -or $tailnetName) {
            return $false
        }

        return ($status.BackendState -in @('NeedsLogin', 'NoState', 'Stopped'))
    } catch {
        return $false
    }
}

function Test-PrefsLookUnconfigured {
    param([Parameter(Mandatory)][string]$Exe)

    try {
        $raw = & $Exe debug prefs 2>&1 | Out-String
        if (-not $raw) {
            return $false
        }

        $prefs = $raw | ConvertFrom-Json
        if ($prefs.LoggedOut -ne $true) {
            return $false
        }

        if ($null -ne $prefs.UserProfile) {
            return $false
        }

        if ($null -ne $prefs.Persist) {
            if ($prefs.Persist.UserProfile -or $prefs.Persist.LoginName) {
                return $false
            }
        }

        return $true
    } catch {
        return $false
    }
}

#region HomePictures-ProfilesJson
# Official switch --list --json items use id, nickname, tailnet, account, selected.
function Test-ProfilesJsonLookUnconfigured {
    param([Parameter(Mandatory)][string]$Json)

    try {
        if (-not $Json) {
            return $false
        }

        $trimmed = $Json.Trim()
        if ($trimmed -eq '[]') {
            return $true
        }

        $profiles = $trimmed | ConvertFrom-Json
        if ($null -eq $profiles) {
            return $false
        }

        $items = @($profiles)
        return ($items.Count -eq 0)
    } catch {
        return $false
    }
}
#endregion HomePictures-ProfilesJson

function Test-ProfilesLookUnconfigured {
    param([Parameter(Mandatory)][string]$Exe)

    try {
        $raw = & $Exe switch --list --json 2>&1 | Out-String
        return (Test-ProfilesJsonLookUnconfigured -Json $raw)
    } catch {
        return $false
    }
}

function Test-TailscaleAlreadyConfigured {
    param([Parameter(Mandatory)][string]$Exe)

    $statusFresh = Test-StatusLooksUnconfigured -Exe $Exe
    $prefsFresh = Test-PrefsLookUnconfigured -Exe $Exe
    $profilesFresh = Test-ProfilesLookUnconfigured -Exe $Exe
    return -not ($statusFresh -and $prefsFresh -and $profilesFresh)
}

function Protect-AuthKeyFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Value
    )

    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Value, $utf8)
    $acl = Get-Acl -LiteralPath $Path
    $acl.SetAccessRuleProtection($true, $false)
    $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().User
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $user,
        'FullControl',
        'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl -LiteralPath $Path -AclObject $acl
}

try {
    $exe = Get-TailscaleExe
    if (-not $exe) {
        throw "Tailscale was not found. Install it from the Camera Access setup page first."
    }

    if (Test-TailscaleAlreadyConfigured -Exe $exe) {
        Write-WarnLine "Tailscale already has an account on this PC."
        Write-Info "HomePictures will not switch, log out, reset, or replace that account."
        Write-Info "Sign in to Camera Access from the Tailscale app using the shared account on the setup page, or sign out yourself first."
        Write-Info "Delete this downloaded script after use. It contains a sign-in secret."
        try {
            Open-SetupWizard
        } catch {
            Write-WarnLine "Could not open the setup page automatically. Open https://cctv.mpdee.uk/setup"
            $script:SkipWait = $false
        }
        exit 2
    }

    $keyPath = Join-Path $env:TEMP ('hp-ts-auth-' + [guid]::NewGuid().ToString('N') + '.key')
    try {
        Protect-AuthKeyFile -Path $keyPath -Value $AuthKeyMaterial
        $fileArg = 'file:' + $keyPath
        & $exe up --auth-key=$fileArg
        if ($LASTEXITCODE -ne 0) {
            throw "Tailscale sign-in did not complete."
        }
        Write-Info "Camera Access sign-in finished. Opening the setup page."
        Write-Info "Delete this downloaded script after use. It contains a sign-in secret."
        Open-SetupWizard -Flag 'signedin'
    } finally {
        if (Test-Path -LiteralPath $keyPath) {
            Remove-Item -LiteralPath $keyPath -Force -ErrorAction SilentlyContinue
        }
    }
} catch {
    Write-Host ""
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Info "This helper was not used to finish sign-in."
    exit 1
} finally {
    if (-not $script:SkipWait) {
        Wait-ForReader
    }
}
`;
}

export function buildWindowsSigninLauncher(authKey: string): string {
  const script = buildWindowsSigninScript(authKey);
  return `@echo off
setlocal EnableExtensions
title HomePictures Camera Access sign-in
set "PS1=%TEMP%\\hp-ts-signin-%RANDOM%%RANDOM%.ps1"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$p='%~f0'; $o='%PS1%'; $lines=Get-Content -LiteralPath $p; $i=0; while ($i -lt $lines.Count -and $lines[$i] -ne '${WINDOWS_SIGNIN_SCRIPT_MARKER}') { $i++ }; if ($i -ge $lines.Count) { throw 'Helper script is incomplete.' }; $lines[($i+1)..($lines.Count-1)] | Set-Content -LiteralPath $o -Encoding UTF8"
if errorlevel 1 (
  echo The sign-in helper could not start.
  pause
  exit /b 1
)
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PS1%"
set "ERR=%ERRORLEVEL%"
if exist "%PS1%" del /f /q "%PS1%" >nul 2>&1
exit /b %ERR%

${WINDOWS_SIGNIN_SCRIPT_MARKER}
${script}
`;
}
